### ISSUE TITLE
local keywords aren't supported in CI configs and the standard linting API

### ISSUE THREAD

**Issue by emmeowzing** [emmeowzing/gitlabci-lint-pre-commit-hook#10]
https://gitlab.com/gitlab-org/gitlab/-/issues/258843 - waiting on this bug to be closed so this module can be reworked.

**Comment by bjd2385** [comment]
Maybe there's an API endpoint that'll let us download the merged config, as we can view in the UI, so we can lint that.

**Comment by bjd2385** [comment]
https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/issues/213
https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/issues/485

Some additional context on this one
